// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmdqdtfmnpfaiyqgsqak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZHFkdGZtbnBmYWl5cWdzcWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjY0NzQsImV4cCI6MjA3Mzg0MjQ3NH0.TblI8dxu0vSIkrvYXNf60gHXFL32nAR6Gfn4cva4KVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});